version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: guide-smiths-node-challenge-image
    container_name: guide-smiths-node-challenge-container
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    command: yarn run dev
